### ISSUE TITLE
A little issue on hyperlink

### ISSUE THREAD

**Issue by JadaGates** [uzh-rpg/event-based_vision_resources#91]
> Zhu et. al. CVPR 2019,
> Unsupervised Event-Based Learning of Optical Flow, Depth, and Egomotion.

I belive you intending add links to the paper while you have added it to the author.

**Comment by guillermogb** [comment]
Hi,
Can you be more specific on what the error is? What line in the current master branch?
Thanks

**Comment by JadaGates** [comment]
Hi,
It's locate at the last row of "Monocular Depth Estimation". I suggest you can use ctrl/command + F to search for "Unsupervised Event-Based Learning of Optical Flow, Depth, and Egomotion".

However, I'm not sure whether it's an error which should be corrected. It's totally upon you. 

Thank you for  your contribution to this field.

**Comment by guillermogb** [comment]
Hi,

I think the link is correct, for maintenance reasons.
We write "Author et al. CVPR YYYY" and put a link to the main definition of this entry (that is, in this case, the link #Zhu19cvpr).  When you click on "Author et al. CVPR YYYY" it will take you to the location on the page where the information about the paper is (in this case, to the correct entry in the section "Optical Flow Estimation").
In this way, if a paper touches upon multiple topics (for example optical flow estimation and depth estimation), we have one main definition and one or more links to it. It is intended this way so that we need to make sure that the links to the content (PDF, video, project page, etc) are maintained only at one location (the main definition) if they are updated.

Take another example:
Kim et al., BMVC 2014, Simultaneous Mosaicing and Tracking with an Event Camera.
- The main entry is in the section "Intensity-Image Reconstruction from events", which contains links to the PDF, the video and some related code. 
- There are also links to this paper on the section "Visual Odometry / SLAM" and on "Algorithms". However, these "secondary" entries do not contain links to the pdf or the video.

Thanks for pointing it out. I corrected some punctuation that was not consistent.
